### ISSUE TITLE
Reading from level.dat isn't allowed sr.c speedrunning

### ISSUE THREAD

**Issue by AbyssStudios** [NinjaSnail1080/maac#1]
This program reads from the level.dat file, but this isn't allowed if you want a verified run on speedrun.com.

**Comment by NinjaSnail1080** [comment]
This application has been approved by one of the mods, and the other app I made, an in game timer, was also approved even though it also reads from level.dat. Since it doesn't display any information that would give the player an unfair advantage, it's fine to use
